### ISSUE TITLE
Why hard code /svr

### ISSUE THREAD

**Issue by mrplow** [ecobytes/docker-nginx-gen-letsencrypt#1]
Just replace /svr/ with ./ in the code right?

**Comment by almereyda** [comment]
Yes, this sounds reasonable. `/srv` is a pattern we are using at @ecobytes to pollute machines in predictable locations only.

**Comment by pierreozoux** [comment]
@mrplow I forked if you want: https://github.com/indiehosters/nginx/

Let me know if you have any issues.
